version: "3"
services:
  app:
    container_name: app
    build: .
    ports:
      - '5000:5000'
    networks:
      - my-networks

  openldap:
    container_name: openldap
    image: bitnami/openldap:latest
    ports:
      - '389:1389'
      - '636:1636'
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_USERS=user01,user02
      - LDAP_PASSWORDS=password1,password2
    networks:
      - my-networks

networks:
  my-networks: